name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  STORAGE_ACCOUNT_RG_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
  STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0

      - name: Configure Terraform backend
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "azurerm" {
              resource_group_name  = "${{ env.STORAGE_ACCOUNT_RG_NAME }}"
              storage_account_name = "${{ env.STORAGE_ACCOUNT_NAME }}"
              container_name       = "${{ env.STORAGE_CONTAINER_NAME }}"
              key                  = "terraform.tfstate"
              access_key           = "${{ env.STORAGE_ACCESS_KEY }}"
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init
        

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve
      
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
      #   working-directory: ./terraform
